const videos={
 opp_dj:'videos/opp_dj.mp4',opp_music:'videos/opp_music.mp4',opp_football:'videos/opp_football.mp4',opp_chef:'videos/opp_chef.mp4',opp_art:'videos/opp_art.mp4',opp_tech:'videos/opp_tech.mp4',
 talent_football:'videos/talent_football.mp4',talent_dj:'videos/talent_dj.mp4',talent_music:'videos/talent_music.mp4',talent_chef:'videos/talent_chef.mp4'
};
const images={
 opp_dj:'assets/opp_dj.jpg',opp_music:'assets/opp_music.jpg',opp_football:'assets/opp_football.jpg',opp_chef:'assets/opp_chef.jpg',opp_art:'assets/opp_art.jpg',opp_tech:'assets/opp_tech.jpg',
 talent_football:'assets/talent_football.jpg',talent_dj:'assets/talent_dj.jpg',talent_music:'assets/talent_music.jpg',talent_chef:'assets/talent_chef.jpg'
};
const opportunities=[
{id:1,title:'DJ Skills Bootcamp',org:'Pulse Academy',cat:'Music',loc:'Giza',date:'Oct 25–26',type:'Opportunity',icon:'🎧',video:videos.opp_dj,image:images.opp_dj,desc:'Two-day practical DJ bootcamp covering transitions, track selection and live setup.',tags:['DJing','Beginner','Workshop'],followers:18200},
{id:2,title:'Producer Jam: After Dark',org:'Cairo Sound Lab',cat:'Music',loc:'Cairo',date:'Friday',type:'Opportunity',icon:'🎛️',video:videos.opp_music,image:images.opp_music,desc:'A late-night producer meetup for beatmakers, vocalists and musicians.',tags:['Production','Jams','Music'],followers:9600},
{id:3,title:'Youth Football Open Trial',org:'Nile Sports Academy',cat:'Sports',loc:'Giza',date:'Oct 10',type:'Opportunity',icon:'⚽',video:videos.opp_football,image:images.opp_football,desc:'Open trial for young players looking to join the academy development program.',tags:['Football','Trial','16–21'],followers:27400},
{id:4,title:'Young Chef Challenge',org:'Taste Makers',cat:'Culinary',loc:'Cairo',date:'Oct 24',type:'Opportunity',icon:'🍳',video:videos.opp_chef,image:images.opp_chef,desc:'A cooking competition for emerging home cooks and aspiring chefs.',tags:['Cooking','Challenge','Competition'],followers:11200},
{id:5,title:'Creative Visual Lab',org:'Studio 27',cat:'Arts',loc:'Online',date:'Oct 12',type:'Opportunity',icon:'🎨',video:videos.opp_art,image:images.opp_art,desc:'Creative workshop exploring photography, visual identity and storytelling.',tags:['Design','Photography','Workshop'],followers:8400},
{id:6,title:'Build Night: AI Edition',org:'Tech House Egypt',cat:'Tech',loc:'Cairo',date:'Oct 16–17',type:'Opportunity',icon:'💻',video:videos.opp_tech,image:images.opp_tech,desc:'Developers and designers team up to prototype useful AI products.',tags:['AI','Hackathon','Tech'],followers:19600}
];
const talents=[
{id:101,title:'Football Highlights',org:'Ahmed Hassan',cat:'Sports',loc:'Cairo',date:'2h ago',type:'Talent',icon:'⚽',video:videos.talent_football,image:images.talent_football,desc:'Winger highlights — pace, 1v1s and finishing. Looking for academy trials.',tags:['Football','Winger','Intermediate'],followers:1240,following:311},
{id:102,title:'Late Night DJ Set',org:'Mariam Saad',cat:'Music',loc:'Giza',date:'5h ago',type:'Talent',icon:'🎧',video:videos.talent_dj,image:images.talent_dj,desc:'House / afro-house practice set. Looking for DJ events and collaborations.',tags:['DJ','House','Live Set'],followers:3890,following:422},
{id:103,title:'Original Vocal Session',org:'Youssef Adel',cat:'Music',loc:'Cairo',date:'1d ago',type:'Talent',icon:'🎤',video:videos.talent_music,image:images.talent_music,desc:'Original vocal performance. Open to producers, writers and live sessions.',tags:['Singer','Vocals','Original'],followers:2160,following:287},
{id:104,title:'Signature Dish',org:'Salma Nour',cat:'Culinary',loc:'Cairo',date:'1d ago',type:'Talent',icon:'🍳',video:videos.talent_chef,image:images.talent_chef,desc:'My take on a modern Egyptian dish. Looking for chef challenges and workshops.',tags:['Chef','Cooking','Egyptian'],followers:1780,following:199}
];
const allPosts=[...opportunities,...talents];
let saved=JSON.parse(localStorage.getItem('syncrSaved2')||'[]'),likes=JSON.parse(localStorage.getItem('syncrLikes')||'[]'),follows=JSON.parse(localStorage.getItem('syncrFollows')||'[]'),apps=JSON.parse(localStorage.getItem('syncrApps')||'[]');
let profile=JSON.parse(localStorage.getItem('syncrProfile')||JSON.stringify({name:'Omar Nosseir',headline:'Music Producer · Singer · Creative Explorer',about:'I am into music production, discovering new sounds, creative projects and meeting people who are building something.',skills:['Music Production','Singing','DJing','Creative'],followers:214,following:138}));
let feedMode='All',category='',query='',selectedApplication=null,recognition=null,toastTimer;
function persist(){localStorage.setItem('syncrSaved2',JSON.stringify(saved));localStorage.setItem('syncrLikes',JSON.stringify(likes));localStorage.setItem('syncrFollows',JSON.stringify(follows));localStorage.setItem('syncrApps',JSON.stringify(apps));localStorage.setItem('syncrProfile',JSON.stringify(profile));document.getElementById('savedCount').textContent=saved.length}
function toggleTheme(){const dark=!document.body.classList.contains('dark');document.body.classList.toggle('dark',dark);localStorage.setItem('syncrTheme',dark?'dark':'light');document.getElementById('themeBtn').textContent=dark?'☀':'☾'}
function loadTheme(){const d=localStorage.getItem('syncrTheme')==='dark';document.body.classList.toggle('dark',d);document.getElementById('themeBtn').textContent=d?'☀':'☾'}
function showPage(id){document.querySelectorAll('.page').forEach(x=>x.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav-btn').forEach(x=>x.classList.remove('active'));if(id==='home')document.querySelector('.nav-btn').classList.add('active');if(id==='saved')renderSaved();if(id==='applications')renderApps();if(id==='profile')renderProfile();window.scrollTo({top:0,behavior:'smooth'})}
function toggleFilters(){document.getElementById('filters').classList.toggle('hidden')}
function setFeedFilter(mode,btn){feedMode=mode;document.querySelectorAll('.chip').forEach(x=>x.classList.remove('selected'));btn.classList.add('selected');renderFeed()}
function resetFilters(){category='';document.getElementById('categoryFilter').value='';document.getElementById('roleFilter').value='';document.getElementById('locationFilter').value='';renderFeed()}
function filtered(){const cat=document.getElementById('categoryFilter').value||category,role=document.getElementById('roleFilter').value,loc=document.getElementById('locationFilter').value;let list=allPosts.filter(p=>(feedMode==='All'||p.type===feedMode)&&(!role||p.type===role)&&(!cat||p.cat===cat)&&(!loc||p.loc===loc)&&(!query||JSON.stringify(p).toLowerCase().includes(query)));return list.sort((a,b)=>score(b)-score(a))}
function score(p){let s=0;const q=(query||'').toLowerCase();if(q&&JSON.stringify(p).toLowerCase().includes(q))s+=30;if(profile.skills.some(x=>JSON.stringify(p).toLowerCase().includes(x.toLowerCase().split(' ')[0])))s+=25;if(p.type==='Opportunity')s+=5;return s+p.id/1000}
function renderFeed(){const list=filtered();document.getElementById('searchStatus').textContent=query?`${list.length} posts found for “${query}”`:`${list.length} posts · AI-ranked around your interests`;document.getElementById('feedGrid').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><h3>No match yet.</h3><p>Try music, football, DJing, chef, trials, workshops or a talent name.</p></div>`}
function card(p){const liked=likes.includes(p.id),followed=follows.includes(p.org),savedPost=saved.includes(p.id);return `<article class="social-card"><div class="post-media"><img class="post-poster" src="${p.image}" alt="${esc(p.title)}"><video src="${p.video}" poster="${p.image}" muted loop playsinline autoplay preload="auto"></video><div class="media-shade"></div><span class="post-type">${p.type==='Opportunity'?'📣 OPPORTUNITY':'🔥 TALENT'}</span>${score(p)>20?'<span class="ai-match">✦ AI MATCH</span>':''}<div class="post-overlay"><small>${p.cat} · ${p.loc}</small><h3>${p.title}</h3><p>${p.desc}</p></div></div><div class="post-body"><div class="author-row"><button class="author-avatar" onclick="openUser('${esc(p.org)}')">${p.org[0]}</button><div class="author-info"><b>${p.org}</b><small>${p.type==='Opportunity'?'Verified institution · ':''}${formatNum(p.followers||0)} followers</small></div><button class="follow-btn ${followed?'following':''}" onclick="toggleFollow('${esc(p.org)}')">${followed?'Following':'Follow'}</button></div><div class="post-actions"><button class="action ${liked?'active':''}" onclick="toggleLike(${p.id})">${liked?'♥':'♡'} ${formatNum((p.likes||0)+(liked?1:0))}</button><button class="action" onclick="sharePost(${p.id})">↗ Share</button><button class="action save ${savedPost?'active':''}" onclick="toggleSave(${p.id})">${savedPost?'♥ Saved':'＋ Save'}</button></div><div class="post-tags">${p.tags.map(t=>`<span>#${t.replace(/\s/g,'')}</span>`).join('')}</div></div></article>`}
function esc(s){return s.replace(/'/g,"\\'")}
function formatNum(n){return n>=1000?(n/1000).toFixed(n>=10000?0:1)+'K':String(n)}
function toggleLike(id){likes=likes.includes(id)?likes.filter(x=>x!==id):[...likes,id];persist();renderFeed();renderFypCurrent()}
function toggleFollow(name){follows=follows.includes(name)?follows.filter(x=>x!==name):[...follows,name];persist();renderFeed();showToast(follows.includes(name)?`Following ${name}`:`Unfollowed ${name}`)}
function toggleSave(id){saved=saved.includes(id)?saved.filter(x=>x!==id):[...saved,id];persist();renderFeed();renderSaved();renderFypCurrent();showToast(saved.includes(id)?'Saved':'Removed from saved')}
function renderSaved(){const list=allPosts.filter(x=>saved.includes(x.id));document.getElementById('savedGrid').innerHTML=list.length?list.map(card).join(''):`<div class="empty"><h3>Nothing saved yet.</h3><p>Save an opportunity or talent post.</p></div>`}
function sharePost(id){navigator.clipboard?.writeText(location.href+`#post-${id}`);showToast('Post link copied ✦')}
function startFYP(){setFypMode('All');document.getElementById('fypOverlay').classList.remove('hidden');document.body.style.overflow='hidden';renderFyp()}
function setFypMode(mode){feedMode=mode;document.querySelectorAll('.fyp-mode button').forEach(x=>x.classList.remove('active'));const idx=mode==='All'?0:mode==='Opportunity'?1:2;document.querySelectorAll('.fyp-mode button')[idx].classList.add('active');renderFyp()}
function renderFyp(){const list=filtered();const feed=document.getElementById('fypFeed');feed.innerHTML=list.length?list.map(p=>fypSlide(p)).join(''):`<div class="fyp-empty">No posts match this filter.</div>`;wireVideos(feed)}
function wireVideos(root){const vids=[...root.querySelectorAll('video')];vids.forEach(v=>{v.muted=true;v.playsInline=true;v.setAttribute('playsinline','');v.setAttribute('webkit-playsinline','');v.addEventListener('error',()=>{v.classList.add('video-failed')},{once:true});v.addEventListener('loadeddata',()=>{if(v.closest('.fyp-slide')?.getBoundingClientRect().top===0)v.play().then(()=>v.closest('.fyp-slide')?.querySelector('.video-play')?.classList.add('hidden')).catch(()=>{})},{once:true})});if('IntersectionObserver' in window){const io=new IntersectionObserver(entries=>entries.forEach(e=>{const v=e.target;if(e.isIntersecting&&e.intersectionRatio>.65){v.muted=true;v.play().then(()=>v.closest('.fyp-slide')?.querySelector('.video-play')?.classList.add('hidden')).catch(()=>{v.closest('.fyp-slide')?.classList.add('tap-to-play')})}else v.pause()}),{root:root.classList.contains('fyp-feed')?root:null,threshold:[.65]});vids.forEach(v=>io.observe(v))}else vids.forEach(v=>v.play().catch(()=>{}))}
function fypSlide(p){const liked=likes.includes(p.id),savedPost=saved.includes(p.id),followed=follows.includes(p.org);return `<article class="fyp-slide"><img class="fyp-poster" src="${p.image}" alt=""><video src="${p.video}" poster="${p.image}" autoplay muted loop playsinline preload="auto"></video><button class="video-play" onclick="playVideo(this)">▶</button><div class="fyp-content"><span class="post-type">${p.type==='Opportunity'?'📣 OPPORTUNITY ANNOUNCEMENT':'🔥 TALENT SHOWCASE'}</span>${score(p)>20?'<span class="ai-match">✦ Recommended for you</span>':''}<div class="org">${p.org} · ${p.cat}</div><h2>${p.title}</h2><p>${p.desc}</p><div class="fyp-meta"><span>📍 ${p.loc}</span><span>◷ ${p.date}</span>${p.tags.slice(0,2).map(t=>`<span>#${t}</span>`).join('')}</div><div class="fyp-actions">${p.type==='Opportunity'?`<button class="primary" onclick="openApplication(${p.id})">Apply now →</button>`:`<button class="ghost" onclick="openUser('${esc(p.org)}')">View profile →</button>`}<button class="ghost" onclick="openUser('${esc(p.org)}')">${followed?'Following':'Follow'}</button></div></div><div class="fyp-social"><div class="social-action"><button class="${liked?'active':''}" onclick="toggleLike(${p.id})">${liked?'♥':'♡'}</button><span>${formatNum((p.likes||0)+(liked?1:0))}</span></div><div class="social-action"><button onclick="sharePost(${p.id})">↗</button><span>Share</span></div><div class="social-action"><button class="${savedPost?'active':''}" onclick="toggleSave(${p.id})">🔖</button><span>${savedPost?'Saved':'Save'}</span></div></div></article>`}
function playVideo(btn){const v=btn.parentElement.querySelector('video');v.muted=true;v.play().then(()=>{btn.classList.add('hidden')}).catch(()=>showToast('Press again to play video'))}
function renderFypCurrent(){if(!document.getElementById('fypOverlay').classList.contains('hidden'))renderFyp()}
function closeFYP(){document.getElementById('fypOverlay').classList.add('hidden');document.body.style.overflow=''}
function openUser(name){const p=allPosts.find(x=>x.org===name);if(!p)return;const followed=follows.includes(name),isInstitution=p.type==='Opportunity';document.getElementById('userContent').innerHTML=`<button class="close" onclick="closeUser()">×</button><div class="detail-top"><div class="author-avatar" style="width:78px;height:78px;font-size:28px">${name[0]}</div><div><div class="verified">${isInstitution?'✓ VERIFIED INSTITUTION':'TALENT PROFILE'}</div><h2>${name}</h2><p>${isInstitution?'Opportunity provider · '+p.cat:p.title+' · '+p.cat}</p></div></div><div class="profile-stats" style="margin:20px 0"><span><b>${formatNum(p.followers||0)}</b> followers</span><span><b>${formatNum(p.following||0)}</b> following</span><span><b>${allPosts.filter(x=>x.org===name).length}</b> posts</span></div><p style="color:var(--muted)">${isInstitution?'Follow this institution to see new trials, workshops, challenges and announcements in your FYP.':p.desc}</p><div class="modal-actions"><button class="primary" onclick="toggleFollow('${esc(name)}');openUser('${esc(name)}')">${followed?'Following':'Follow'}</button>${isInstitution?`<button class="ghost" onclick="startFYP();closeUser()">See posts</button>`:''}</div>`;document.getElementById('userModal').classList.remove('hidden')}
function closeUser(){document.getElementById('userModal').classList.add('hidden')}
function openApplication(id){const p=opportunities.find(x=>x.id===id);if(!p)return;selectedApplication=id;document.getElementById('formTitle').textContent=p.title;document.getElementById('formOrg').textContent=`${p.org} · ${p.loc} · ${p.date}`;document.getElementById('applicationModal').classList.remove('hidden')}
function closeApplication(){document.getElementById('applicationModal').classList.add('hidden');selectedApplication=null}
document.getElementById('applicationForm').addEventListener('submit',e=>{e.preventDefault();const p=opportunities.find(x=>x.id===selectedApplication);const record={id:p.id,title:p.title,org:p.org,status:'Submitted',submittedAt:new Date().toISOString(),name:appName.value,email:appEmail.value,phone:appPhone.value,level:appLevel.value,why:appWhy.value,link:appLink.value,file:appFile.files[0]?.name||''};apps=apps.filter(x=>x.id!==p.id);apps.push(record);persist();e.target.reset();fileName.textContent='';closeApplication();showToast('Application submitted ✦');renderApps()});
appFile.addEventListener('change',e=>fileName.textContent=e.target.files[0]?`Attached: ${e.target.files[0].name}`:'');
function renderApps(){const el=document.getElementById('applicationsList');el.innerHTML=apps.length?apps.map(a=>`<div class="application"><div class="app-icon">✦</div><div><h3>${a.title}</h3><p>${a.org} · ${new Date(a.submittedAt).toLocaleString()}</p></div><span class="status">${a.status}</span><div class="application-detail"><div class="timeline"><span class="done">✓ Submitted</span><span>Under Review</span><span>Shortlisted</span><span>Accepted / Not Selected</span></div>${a.file?`<p>Attachment: ${a.file}</p>`:''}</div></div>`).join(''):`<div class="empty"><h3>Your journey starts here.</h3><p>Open the FYP, find an opportunity announcement and apply.</p><button class="primary" onclick="startFYP()">Open FYP →</button></div>`}
function renderProfile(){const l=(profile.name||'O')[0].toUpperCase();profileAvatar.textContent=l;headerAvatar.textContent=l;profileName.textContent=profile.name;profileHeadline.textContent=profile.headline;profileAbout.textContent=profile.about;myFollowers.textContent=profile.followers;myFollowing.textContent=profile.following;myPosts.textContent=allPosts.filter(x=>x.org===profile.name).length||4;profileTags.innerHTML=profile.skills.map(x=>`<span>${x}</span>`).join('');myPostList.innerHTML=talents.slice(0,3).map(p=>`<div class="mini-post"><img src="assets/${p.id===101?'talent_football':p.id===102?'talent_dj':'talent_music'}.jpg" onerror="this.style.display='none'"><div><b>${p.title}</b><small>${p.cat} · ${p.loc}</small></div></div>`).join('')}
function openProfileEditor(){editName.value=profile.name;editHeadline.value=profile.headline;editAbout.value=profile.about;editSkills.value=profile.skills.join(', ');profileModal.classList.remove('hidden')}
function closeProfileEditor(){profileModal.classList.add('hidden')}
profileForm.addEventListener('submit',e=>{e.preventDefault();profile={...profile,name:editName.value.trim(),headline:editHeadline.value.trim(),about:editAbout.value.trim(),skills:editSkills.value.split(',').map(x=>x.trim()).filter(Boolean)};persist();renderProfile();closeProfileEditor();showToast('Profile updated ✦')});
function openDetail(id){const p=opportunities.find(x=>x.id===id);if(!p)return;document.getElementById('detailContent').innerHTML=`<button class="close" onclick="closeModal()">×</button><div class="detail-top"><div class="detail-icon"><video src="${p.video}" autoplay muted loop playsinline style="width:100%;height:100%;object-fit:cover;border-radius:18px"></video></div><div><div class="verified">✓ VERIFIED OPPORTUNITY</div><h2>${p.title}</h2><p>${p.org} · ${p.cat}</p></div></div><div class="detail-meta"><span>📍 ${p.loc}</span><span>◷ ${p.date}</span><span>👤 ${p.type}</span></div><div class="detail-section"><h3>About</h3><p>${p.desc}</p><h3>Requirements</h3><p>${p.tags.join(' · ')}</p></div><div class="modal-actions"><button class="primary" onclick="closeModal();openApplication(${p.id})">Apply now →</button><button class="ghost" onclick="toggleSave(${p.id});closeModal()">${saved.includes(p.id)?'♥ Saved':'＋ Save'}</button></div>`;detailModal.classList.remove('hidden')}
function closeModal(){detailModal.classList.add('hidden')}
function openAI(){aiModal.classList.remove('hidden');aiInput.focus()};function closeAI(){stopVoice();aiModal.classList.add('hidden')}
function sendAI(msg){const q=(msg||aiInput.value).trim();if(!q)return;addBubble(q,'user');aiInput.value='';setTimeout(()=>aiReply(q.toLowerCase()),300)}
function addBubble(t,type){const b=document.createElement('div');b.className='bubble '+type;b.innerHTML=t;chat.appendChild(b);chat.scrollTop=chat.scrollHeight}
function aiReply(q){let m=allPosts.filter(p=>{const h=JSON.stringify(p).toLowerCase();return(q.includes('football')&&h.includes('football'))||(q.includes('dj')&&h.includes('dj'))||(q.includes('music')&&p.cat==='Music')||(q.includes('chef')&&p.cat==='Culinary')||(q.includes('art')&&p.cat==='Arts')||(!q.match(/football|dj|music|chef|art/)&&score(p)>10)}).slice(0,5);if(!m.length)m=allPosts.slice(0,4);addBubble(`I found <b>${m.length}</b> posts across both sides of Syncr — opportunities and talents.`, 'ai');m.forEach(p=>addBubble(`<b>${p.type==='Opportunity'?'📣':'🔥'} ${p.title}</b><br><small>${p.org} · ${p.cat} · ${p.loc}</small>`,'ai'));speak(`I found ${m.length} relevant posts across opportunities and talent.`)}
function speak(t){if('speechSynthesis'in window){speechSynthesis.cancel();speechSynthesis.speak(new SpeechSynthesisUtterance(t))}}
function toggleVoice(){const SR=window.SpeechRecognition||window.webkitSpeechRecognition;if(!SR){showToast('Voice recognition is not supported in this browser');return}if(recognition){stopVoice();return}recognition=new SR();recognition.lang='en-US';recognition.interimResults=false;document.getElementById('voiceState').classList.remove('hidden');voiceBtn.textContent='⏹';recognition.onresult=e=>sendAI(e.results[0][0].transcript);recognition.onerror=()=>showToast('Voice input stopped');recognition.onend=stopVoice;recognition.start()}
function stopVoice(){if(recognition){try{recognition.stop()}catch(e){}recognition=null}voiceState.classList.add('hidden');voiceBtn.textContent='🎙'}
function search(v){query=v.trim().toLowerCase();renderFeed()}
['categoryFilter','roleFilter','locationFilter'].forEach(id=>document.getElementById(id).addEventListener('change',renderFeed));
globalSearch.addEventListener('input',e=>{clearSearch.style.display=e.target.value?'block':'none';search(e.target.value)});clearSearch.addEventListener('click',()=>{globalSearch.value='';clearSearch.style.display='none';search('')});
function showToast(t){toast.textContent=t;toast.classList.add('show');clearTimeout(toastTimer);toastTimer=setTimeout(()=>toast.classList.remove('show'),1800)}
loadTheme();persist();renderProfile();renderFeed();wireVideos(document.getElementById('feedGrid'));
